n=int(input('digite:'))
print('-'*12)
print(f'{n} x {0:2} = {n*0}')
print(f'{n} x {1:2} = {n*1}')
print(f'{n} x {2:2} = {n*2}')
print(f'{n} x {3:2} = {n*3}')
print(f'{n} x {4:2} = {n*4}')
print(f'{n} x {5:2} = {n*5}')
print(f'{n} x {6:2} = {n*6}')
print(f'{n} x {7:2} = {n*7}')
print(f'{n} x {8:2} = {n*8}')
print(f'{n} x {9:2} = {n*9}')
print(f'{n} x {10:2} = {n*10}')
print(f'-'*12)

#print(f'{n} x 0 = {n0} \n{n} x 1 = {n1} \n{n} x 2 = {n2}')
#print(f'{n} x 3 = {n3} \n{n} x 4 = {n4} \n{n} x 5 = {n5}')
#print(f'{n} x 6 = {n6} \n{n} x 7 = {n7} \n{n} x 8 = {n8}')
#print(f'{n} x 9 = {n9} \n{n} x 10 = {n10}')


n = int (input ('Digite um número: '))
print(f'{n} x 1 = {n*1}')
print(f'{n} x 2 = {n*2}')
print(f'{n} x 3 = {n*3}')
print(f'{n} x 4 = {n*4}')
print(f'{n} x 5 = {n*5}')
print(f'{n} x 6 = {n*6}')
print(f'{n} x 7 = {n*7}')
print(f'{n} x 8 = {n*8}')
print(f'{n} x 9 = {n*9}')
print(f'{n} x 10 = {n*10}')
